"""
Mapping between PostgreSQL model columns and Airtable field names.

Each entry: model_column -> list of Airtable field names (first match wins on read,
first name used on write).
"""

FIELD_MAPS = {
    "RentCar": {
        "airtable_base": "appR8ZKP5ygR8o8Q0",
        "airtable_table": "Rent Car",
        "fields": {
            "ref":             ["Referência", "Referencia"],
            "nome":            ["Nome do cliente", "Nome do Cliente"],
            "tel":             ["Número de Telemovel", "Telefone"],
            "email":           ["Email do cliente", "Email"],
            "idade":           ["Idade"],
            "parceiro":        ["Fornecedor/Parceiro", "Parceiro"],
            "carro":           ["Carro", "Modelo de Carro", "Veículo"],
            "estado":          ["Estado de Reserva", "Estado do Reserva", "Estado da Reserva"],
            "pagamento":       ["Estado de Pagamento", "Pagamento"],
            "pickup_data":     ["Data da Pick-up", "Data Pick-up"],
            "pickup_local":    ["Localização Pick-up", "Local Pick-up"],
            "pickup_voo":      ["Voo Pick-up"],
            "pickup_detalhe":  ["Detalhes Pick Up", "Detalhe Pick-up"],
            "dropoff_data":    ["Data do Drop Off", "Data Drop-off"],
            "dropoff_local":   ["Localização Drop-off", "Local Drop-off"],
            "dropoff_voo":     ["Voo Drop-off"],
            "dropoff_detalhe": ["Detalhes Drop Off", "Detalhe Drop-off"],
            "total":           ["Valor da Reserva (€)", "Total"],
            "comissao":        ["Comissão", "Comissao"],
            "duracao":         ["Duração", "Duracao"],
            "extras":          ["Extras"],
            "observacoes":     ["Observações", "Observacoes"],
            "ref_parceiro":    ["Referência Parceiro"],
            "email_enviado":   ["Email Enviado"],
            "review_enviado":  ["Review Enviado"],
            "data_feita":      ["Data Feita a Reserva", "Data Feita", "Created Time"],
        },
    },
    "Atividade": {
        "airtable_base": "appR8ZKP5ygR8o8Q0",
        "airtable_table": "Atividades",
        "fields": {
            "ref":               ["Referência", "Referencia"],
            "nome":              ["Nome do Cliente"],
            "tel":               ["Contacto Telefonico", "Telefone"],
            "email":             ["Email Clientes", "Email"],
            "atividade":         ["Atividade"],
            "categoria":         ["Categoria"],
            "parceiro":          ["Fornecedor/Parceiro", "Parceiro"],
            "pax":               ["Nº Pessoas", "Pessoas"],
            "data":              ["Data da Atividade", "Data"],
            "hora":              ["Hora"],
            "total":             ["Preço Total", "Valor da Reserva (€)", "Total"],
            "comissao":          ["Comissão", "Comissao"],
            "estado":            ["Estado da Reserva"],
            "pagamento":         ["Estado de Pagamento", "Pagamento"],
            "observacoes":       ["Observação", "Observacoes"],
            "local_pickup":      ["Pick-up local", "Local"],
            "stripe_link":       ["Stripe Link"],
            "idiomas":           ["Idiomas"],
            "email_enviado":     ["Email Enviado"],
            "thankyou_enviado":  ["Thank You Enviado"],
            "review_pedida":     ["Review Pedida"],
            "data_feita":        ["Created", "Data Feita", "Created Time"],
        },
    },
    "Parceiro": {
        "airtable_base": "appR8ZKP5ygR8o8Q0",
        "airtable_table": "Parceiros",
        "fields": {
            "nome":     ["Nome", "Name"],
            "email":    ["Email"],
            "telefone": ["Telefone", "Tel"],
            "tipo":     ["Tipo", "Categoria"],
            "ativo":    ["Ativo", "Active"],
        },
    },
    "Tarefa": {
        "airtable_base": "appR8ZKP5ygR8o8Q0",
        "airtable_table": "Tarefas",
        "fields": {
            "descricao":   ["Descrição", "Descricao", "Tarefa"],
            "status":      ["Status", "Estado"],
            "prioridade":  ["Prioridade", "Priority"],
            "responsavel": ["Responsável", "Responsavel"],
            "data":        ["Data"],
            "feita":       ["Feita", "Done"],
        },
    },
    "Nota": {
        "airtable_base": "appR8ZKP5ygR8o8Q0",
        "airtable_table": "Notas",
        "fields": {
            "titulo": ["Título", "Titulo", "Nome"],
            "texto":  ["Texto", "Nota", "Conteúdo"],
            "data":   ["Data", "Created"],
            "cor":    ["Cor"],
        },
    },
    "Sitemap": {
        "airtable_base": "appKhPwEBxolWaO9r",
        "airtable_table": "Sitemap",
        "fields": {
            "nome":                ["Nome de Página", "Nome de Pagina"],
            "estado":              ["Estado"],
            "categoria_principal": ["Categoria Principal"],
            "url":                 ["URL"],
            "categoria":           ["Categoria"],
            "conteudo":            ["Conteúdo", "Conteudo"],
            "modified":            ["Last Modified"],
        },
    },
    "Biblioteca": {
        "airtable_base": "appKhPwEBxolWaO9r",
        "airtable_table": "Biblioteca",
        "fields": {
            "titulo":     ["Answer Title"],
            "gatilho":    ["Trigger", "Customer Question"],
            "resposta":   ["Answer"],
            "categoria":  ["Category"],
            "estado":     ["Status"],
            "observacoes": ["Observação", "Observacao"],
        },
    },
    "MadeiraGuide": {
        "airtable_base": "appKhPwEBxolWaO9r",
        "airtable_table": "Madeira Guide",
        "fields": {
            "titulo":      ["Nome"],
            "categoria":   ["Categoria"],
            "descricao":   ["Descrição", "Descricao"],
            "localizacao": ["Localização", "Localizacao"],
            "estado":      ["Estado"],
            "prioridade":  ["Prioridade"],
            "tags":        ["Tags"],
            "notas":       ["Notas Internas"],
            "recomendado": ["Recomendado?"],
            "preco_nivel": ["Preço Nível", "Preco Nivel"],
            "horario":     ["Horário", "Horario"],
            "distancia":   ["Distância", "Distancia"],
            "dificuldade": ["Dificuldade"],
            "website":     ["Website"],
            "contacto":    ["Contacto"],
        },
    },
    "TemplateMensagem": {
        "airtable_base": "appKhPwEBxolWaO9r",
        "airtable_table": "Templates Mensagens",
        "fields": {
            "name":      ["Name", "Nome"],
            "empresa":   ["Empresa"],
            "categoria": ["Categoria"],
            "contexto":  ["Contexto", "Tópico", "Topico"],
            "msg_en":    ["Message \U0001f1ec\U0001f1e7", "Message", "Mensagem EN"],
            "msg_pt":    ["Message \U0001f1f5\U0001f1f9", "Mensagem PT", "Mensagem"],
            "msg_fr":    ["Message \U0001f1eb\U0001f1f7", "Mensagem FR"],
            "subj_en":   ["Subject \U0001f1ec\U0001f1e7", "Subject", "Assunto EN"],
            "subj_pt":   ["Subject \U0001f1f5\U0001f1f9", "Assunto PT", "Assunto"],
            "idioma":    ["Idioma"],
        },
    },
    "ComissaoParceiro": {
        "airtable_base": "appRGJjirAzgEe46q",
        "airtable_table": "Comissões Parceiros",
        "fields": {
            "parceiro":         ["Parceiro"],
            "mes":              ["Mês", "Mes"],
            "valor":            ["Valor do mês (€)", "Valor"],
            "ajustes":          ["Ajustes / Atrasos (€)"],
            "total":            ["Total a Receber (€)", "Total"],
            "recebido":         ["Recebido?"],
            "data_recebimento": ["Data de Recebimento"],
            "mail_enviado":     ["Mail enviado / pedido?"],
            "acumulado":        ["Acumulado"],
        },
    },
    "RegistoDiario": {
        "airtable_base": "appOrdG5Fsr7N0RmH",
        "airtable_table": "Registos Diários",
        "fields": {
            "data":          ["Data", "Date"],
            "faturacao":     ["Faturação Diária", "Faturacao Diaria"],
            "faturacao_rc":  ["Faturação RC"],
            "faturacao_at":  ["Faturação AT"],
            "notas":         ["Notas do Dia"],
            "responsavel":   ["Responsável"],
        },
    },
    "DespesaFixa": {
        "airtable_base": "appOrdG5Fsr7N0RmH",
        "airtable_table": "Despesas Fixas",
        "fields": {
            "nome":      ["Fornecedor", "Nome", "Descrição"],
            "valor":     ["Valor"],
            "mes":       ["Mês", "Mes", "Notas"],
            "categoria": ["Categoria"],
            "pago":      ["Pago?", "Pago"],
            "fatura":    ["Fatura?", "Fatura"],
        },
    },
    "DespesaVariavel": {
        "airtable_base": "appOrdG5Fsr7N0RmH",
        "airtable_table": "Despesas Variáveis",
        "fields": {
            "nome":      ["Fornecedor", "Nome", "Descrição"],
            "valor":     ["Valor"],
            "mes":       ["Mês", "Mes", "Notas"],
            "categoria": ["Categoria"],
            "pago":      ["Pago?", "Pago"],
            "fatura":    ["Fatura?", "Fatura"],
        },
    },
    "Objetivo": {
        "airtable_base": "appOrdG5Fsr7N0RmH",
        "airtable_table": "Objetivos & Crescimento",
        "fields": {
            "mes":       ["Mês", "Mes"],
            "ano":       ["Ano"],
            "faturacao": ["Faturação", "Faturacao", "Objetivo"],
        },
    },
    "ResumoMensal": {
        "airtable_base": "appOrdG5Fsr7N0RmH",
        "airtable_table": "Resumos Mensais",
        "fields": {
            "mes":       ["Mês", "Mes"],
            "faturacao": ["Faturação", "Faturacao"],
            "comissoes": ["Comissões", "Comissoes"],
            "despesas":  ["Despesas"],
        },
    },
    "CaixaMensal": {
        "airtable_base": "appOrdG5Fsr7N0RmH",
        "airtable_table": "Caixa Mensal",
        "fields": {},  # raw pass-through
    },
}
