"""initial models - 16 tables

Revision ID: e4abd78233ec
Revises: 
Create Date: 2026-04-05 19:11:21.240560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4abd78233ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=50), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('tel', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('atividade', sa.String(length=200), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('parceiro', sa.String(length=200), nullable=True),
    sa.Column('pax', sa.String(length=20), nullable=True),
    sa.Column('data', sa.String(length=50), nullable=True),
    sa.Column('hora', sa.String(length=20), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comissao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('pagamento', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('local_pickup', sa.String(length=300), nullable=True),
    sa.Column('stripe_link', sa.String(length=500), nullable=True),
    sa.Column('idiomas', sa.String(length=100), nullable=True),
    sa.Column('email_enviado', sa.Boolean(), nullable=True),
    sa.Column('thankyou_enviado', sa.Boolean(), nullable=True),
    sa.Column('review_pedida', sa.Boolean(), nullable=True),
    sa.Column('data_feita', sa.String(length=50), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('atividade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atividade_airtable_id'), ['airtable_id'], unique=True)

    op.create_table('biblioteca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=True),
    sa.Column('gatilho', sa.Text(), nullable=True),
    sa.Column('resposta', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biblioteca', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biblioteca_airtable_id'), ['airtable_id'], unique=True)

    op.create_table('caixa_mensal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_fields', sa.JSON(), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caixa_mensal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caixa_mensal_airtable_id'), ['airtable_id'], unique=True)

    op.create_table('comissao_parceiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parceiro', sa.String(length=200), nullable=True),
    sa.Column('mes', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ajustes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recebido', sa.Boolean(), nullable=True),
    sa.Column('data_recebimento', sa.String(length=50), nullable=True),
    sa.Column('mail_enviado', sa.Boolean(), nullable=True),
    sa.Column('acumulado', sa.Boolean(), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comissao_parceiro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comissao_parceiro_airtable_id'), ['airtable_id'], unique=True)

    op.create_table('despesa_fixa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mes', sa.String(length=50), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.Column('fatura', sa.Boolean(), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('despesa_fixa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_despesa_fixa_airtable_id'), ['airtable_id'], unique=True)

    op.create_table('despesa_variavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mes', sa.String(length=50), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.Column('fatura', sa.Boolean(), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('despesa_variavel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_despesa_variavel_airtable_id'), ['airtable_id'], unique=True)

    op.create_table('madeira_guide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('localizacao', sa.String(length=300), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('prioridade', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('recomendado', sa.Boolean(), nullable=True),
    sa.Column('preco_nivel', sa.String(length=50), nullable=True),
    sa.Column('horario', sa.String(length=200), nullable=True),
    sa.Column('distancia', sa.String(length=100), nullable=True),
    sa.Column('dificuldade', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('contacto', sa.String(length=200), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('madeira_guide', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_madeira_guide_airtable_id'), ['airtable_id'], unique=True)

    op.create_table('nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('data', sa.String(length=50), nullable=True),
    sa.Column('cor', sa.String(length=30), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nota', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nota_airtable_id'), ['airtable_id'], unique=True)

    op.create_table('objetivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('faturacao', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objetivo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objetivo_airtable_id'), ['airtable_id'], unique=True)

    op.create_table('parceiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parceiro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parceiro_airtable_id'), ['airtable_id'], unique=True)

    op.create_table('registo_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=50), nullable=True),
    sa.Column('faturacao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('faturacao_rc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('faturacao_at', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registo_diario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registo_diario_airtable_id'), ['airtable_id'], unique=True)

    op.create_table('rent_car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=50), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('tel', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('idade', sa.String(length=20), nullable=True),
    sa.Column('parceiro', sa.String(length=200), nullable=True),
    sa.Column('carro', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('pagamento', sa.String(length=50), nullable=True),
    sa.Column('pickup_data', sa.String(length=50), nullable=True),
    sa.Column('pickup_local', sa.String(length=300), nullable=True),
    sa.Column('pickup_voo', sa.String(length=50), nullable=True),
    sa.Column('pickup_detalhe', sa.Text(), nullable=True),
    sa.Column('dropoff_data', sa.String(length=50), nullable=True),
    sa.Column('dropoff_local', sa.String(length=300), nullable=True),
    sa.Column('dropoff_voo', sa.String(length=50), nullable=True),
    sa.Column('dropoff_detalhe', sa.Text(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comissao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.Column('extras', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ref_parceiro', sa.String(length=100), nullable=True),
    sa.Column('email_enviado', sa.Boolean(), nullable=True),
    sa.Column('review_enviado', sa.Boolean(), nullable=True),
    sa.Column('data_feita', sa.String(length=50), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rent_car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rent_car_airtable_id'), ['airtable_id'], unique=True)

    op.create_table('resumo_mensal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.String(length=50), nullable=True),
    sa.Column('faturacao', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('comissoes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('despesas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumo_mensal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumo_mensal_airtable_id'), ['airtable_id'], unique=True)

    op.create_table('sitemap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('categoria_principal', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('categoria', sa.String(length=200), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('modified', sa.String(length=50), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sitemap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sitemap_airtable_id'), ['airtable_id'], unique=True)

    op.create_table('tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('data', sa.String(length=50), nullable=True),
    sa.Column('feita', sa.Boolean(), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarefa_airtable_id'), ['airtable_id'], unique=True)

    op.create_table('template_mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('empresa', sa.String(length=200), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('contexto', sa.Text(), nullable=True),
    sa.Column('msg_en', sa.Text(), nullable=True),
    sa.Column('msg_pt', sa.Text(), nullable=True),
    sa.Column('msg_fr', sa.Text(), nullable=True),
    sa.Column('subj_en', sa.String(length=300), nullable=True),
    sa.Column('subj_pt', sa.String(length=300), nullable=True),
    sa.Column('idioma', sa.String(length=10), nullable=True),
    sa.Column('airtable_id', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template_mensagem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_mensagem_airtable_id'), ['airtable_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_mensagem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_mensagem_airtable_id'))

    op.drop_table('template_mensagem')
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarefa_airtable_id'))

    op.drop_table('tarefa')
    with op.batch_alter_table('sitemap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sitemap_airtable_id'))

    op.drop_table('sitemap')
    with op.batch_alter_table('resumo_mensal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumo_mensal_airtable_id'))

    op.drop_table('resumo_mensal')
    with op.batch_alter_table('rent_car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rent_car_airtable_id'))

    op.drop_table('rent_car')
    with op.batch_alter_table('registo_diario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registo_diario_airtable_id'))

    op.drop_table('registo_diario')
    with op.batch_alter_table('parceiro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parceiro_airtable_id'))

    op.drop_table('parceiro')
    with op.batch_alter_table('objetivo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objetivo_airtable_id'))

    op.drop_table('objetivo')
    with op.batch_alter_table('nota', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nota_airtable_id'))

    op.drop_table('nota')
    with op.batch_alter_table('madeira_guide', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_madeira_guide_airtable_id'))

    op.drop_table('madeira_guide')
    with op.batch_alter_table('despesa_variavel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_despesa_variavel_airtable_id'))

    op.drop_table('despesa_variavel')
    with op.batch_alter_table('despesa_fixa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_despesa_fixa_airtable_id'))

    op.drop_table('despesa_fixa')
    with op.batch_alter_table('comissao_parceiro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comissao_parceiro_airtable_id'))

    op.drop_table('comissao_parceiro')
    with op.batch_alter_table('caixa_mensal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caixa_mensal_airtable_id'))

    op.drop_table('caixa_mensal')
    with op.batch_alter_table('biblioteca', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biblioteca_airtable_id'))

    op.drop_table('biblioteca')
    with op.batch_alter_table('atividade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atividade_airtable_id'))

    op.drop_table('atividade')
    # ### end Alembic commands ###
